name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    runs-on: windows-2022
    
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
        
    env:
      Solution_Name: MauiFeed
      Project_Name: MauiFeed.WinUI
      working-directory: ./src/MauiFeed.WinUI
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install Windows App SDK
      shell: powershell
      run: Invoke-webrequest -uri https://aka.ms/windowsappsdk/1.2/1.2.230118.102/windowsappruntimeinstall-x64.exe -OutFile windowsappruntimeinstall-x64.exe ; &.\windowsappruntimeinstall-x64.exe

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Create the app (Packaged)
      run: dotnet publish -r win10-$env:Platform -c $env:Configuration -p:Platform=$env:Platform -p:IsUnpackaged=false -o=app\packaged-$env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        
    # Create the app by building and publishing the project
    - name: Create the app (Unpackaged)
      run: dotnet publish -r win10-$env:Platform -c $env:Configuration -p:Platform=$env:Platform -p:IsUnpackaged=true -o=app\unpackaged-$env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    # Upload the app
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: Upload app
        path: src\\${{ env.Project_Name }}\\bin\app\
