//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiFeed.Translations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiFeed.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFeedButton {
            get {
                return ResourceManager.GetString("AddFeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddFolderLabel {
            get {
                return ResourceManager.GetString("AddFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add To Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddToFolderLabel {
            get {
                return ResourceManager.GetString("AddToFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Unread に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllUnreadLabel {
            get {
                return ResourceManager.GetString("AllUnreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MauiFeed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DarkThemeLabel {
            get {
                return ResourceManager.GetString("DarkThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DatabaseExportLabel {
            get {
                return ResourceManager.GetString("DatabaseExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DatabaseImportLabel {
            get {
                return ResourceManager.GetString("DatabaseImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DatabaseLabel {
            get {
                return ResourceManager.GetString("DatabaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultThemeLabel {
            get {
                return ResourceManager.GetString("DefaultThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeedLabel {
            get {
                return ResourceManager.GetString("FeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feed URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeedUrlLabel {
            get {
                return ResourceManager.GetString("FeedUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderLabel {
            get {
                return ResourceManager.GetString("FolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderNameLabel {
            get {
                return ResourceManager.GetString("FolderNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google News に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleNewsService {
            get {
                return ResourceManager.GetString("GoogleNewsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Business に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleSectionBusiness {
            get {
                return ResourceManager.GetString("GoogleSectionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Health に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleSectionHealth {
            get {
                return ResourceManager.GetString("GoogleSectionHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleSectionNation {
            get {
                return ResourceManager.GetString("GoogleSectionNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Science に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleSectionScience {
            get {
                return ResourceManager.GetString("GoogleSectionScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Technology に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleSectionTechnology {
            get {
                return ResourceManager.GetString("GoogleSectionTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoogleSectionWorld {
            get {
                return ResourceManager.GetString("GoogleSectionWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Read Articles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HideAllReadLabel {
            get {
                return ResourceManager.GetString("HideAllReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseLanguage {
            get {
                return ResourceManager.GetString("JapaneseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LightThemeLabel {
            get {
                return ResourceManager.GetString("LightThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocalLabel {
            get {
                return ResourceManager.GetString("LocalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark All As Read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarkAllAsReadLabel {
            get {
                return ResourceManager.GetString("MarkAllAsReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark All As Unread に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarkAllAsUnrealLabel {
            get {
                return ResourceManager.GetString("MarkAllAsUnrealLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark As Read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarkAsReadLabel {
            get {
                return ResourceManager.GetString("MarkAsReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add As Favorite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarkAsStarLabel {
            get {
                return ResourceManager.GetString("MarkAsStarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark As Unread に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarkAsUnreadLabel {
            get {
                return ResourceManager.GetString("MarkAsUnreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move To Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveToFolderLabel {
            get {
                return ResourceManager.GetString("MoveToFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoSelectionLabel {
            get {
                return ResourceManager.GetString("NoSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open In Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenInBrowserLabel {
            get {
                return ResourceManager.GetString("OpenInBrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share Link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenShareLabel {
            get {
                return ResourceManager.GetString("OpenShareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refreshing {0} of {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshingLabel {
            get {
                return ResourceManager.GetString("RefreshingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveFeedLabel {
            get {
                return ResourceManager.GetString("RemoveFeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveFolderLabel {
            get {
                return ResourceManager.GetString("RemoveFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove From Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveFromFolderLabel {
            get {
                return ResourceManager.GetString("RemoveFromFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove From Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveStarLabel {
            get {
                return ResourceManager.GetString("RemoveStarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smart Feeds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SmartFeedsLabel {
            get {
                return ResourceManager.GetString("SmartFeedsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StarredLabel {
            get {
                return ResourceManager.GetString("StarredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateFolderLabel {
            get {
                return ResourceManager.GetString("UpdateFolderLabel", resourceCulture);
            }
        }
    }
}
